[workspace]
authors = ["yusra <nvd.yusra@gmail.com>"]
channels = ["conda-forge"]
name = "BINF-5507-materials"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.6,<3"
python = ">=3.13.3,<3.14"
matplotlib = ">=3.10.3,<4"
pandas = ">=2.2.3,<3"
scikit-learn = ">=1.6.1,<2"
ipykernel = ">=6.29.5,<7"
scikit-survival = ">=0.24.1,<0.25"
pip = ">=24.3.1,<25"
ipywidgets = ">=8.1.5,<9"
lifelines = ">=0.30.0,<0.31"
statsmodels = ">=0.14.4,<0.15"
jinja2 = ">=3.1.5,<4"
ucimlrepo = ">=0.0.7,<0.0.8"
pydicom = ">=2.4.4,<3"
nibabel = ">=5.3.2,<6"
umap-learn = ">=0.5.7,<0.6"


[pypi-dependencies]
scikit-learn-extra = ">=0.3.0, <0.4"
pyradiomics-bhklab = ">=3.1.4, <4"